on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Testing
        run: mvn test
      - name: Build and run
        run: mvn package
             java -Xmx1G -jar target/UnoTest-1.0-SNAPSHOT.jar inputs/lng-4.txt
